spring.application.name=hackconnect

# Database Properties
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/hackconnect?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:Manoj$2005}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# CORS Configuration
cors.allowed.origins=${FRONTEND_URL:http://localhost:5173}

# JPA/Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT Properties
jwt.secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
jwt.expiration=86400000

# Server Port
server.port=8080
